CIRCLE_TO_STATE = {
    'VIJAYAWADA': 'Andhra Pradesh', 'TIRUPATI': 'Andhra Pradesh', 'GUNTUR': 'Andhra Pradesh', 'RAJAHMUNDRY': 'Andhra Pradesh', 'NELLORE': 'Andhra Pradesh', 'VISAKHAPATNAM': 'Andhra Pradesh', 'KURNOOL': 'Andhra Pradesh',
    'PASIGHAT': 'Arunachal Pradesh', 'ITANAGAR': 'Arunachal Pradesh',
    'DIBRUGARH': 'Assam', 'GUWAHATI': 'Assam',
    'PATNA': 'Bihar', 'MUZAFFARPUR': 'Bihar',
    'RAIPUR': 'Chhattisgarh', 'BILASPUR': 'Chhattisgarh',
    'PANAJI': 'Goa', 'MARGAO': 'Goa',
    'VADODARA': 'Gujarat', 'AHMEDABAD': 'Gujarat', 'SURAT': 'Gujarat', 'JAMNAGAR': 'Gujarat', 'RAJKOT': 'Gujarat', 'BHAVNAGAR': 'Gujarat', 'GANDHINAGAR': 'Gujarat',
    'GURUGRAM': 'Haryana', 'FARIDABAD': 'Haryana',
    'SHIMLA': 'Himachal Pradesh', 'DHARAMSHALA': 'Himachal Pradesh',
    'JAMSHEDPUR': 'Jharkhand', 'RANCHI': 'Jharkhand',
    'HUBBALLI': 'Karnataka', 'MYSURU': 'Karnataka', 'BENGALURU': 'Karnataka', 'BALLARI': 'Karnataka', 'KALABURAGI': 'Karnataka', 'BENGALURU NORTH': 'Karnataka', 'BENGALURU SOUTH': 'Karnataka', 'MANGALURU': 'Karnataka', 'BENGALURU EAST': 'Karnataka', 'BELAGAVI': 'Karnataka',
    'TRIVANDRUM': 'Kerala', 'KOCHI': 'Kerala', 'KANNUR': 'Kerala', 'THRISSUR': 'Kerala', 'KOZHIKODE': 'Kerala', 'PALAKKAD': 'Kerala', 'KOLLAM': 'Kerala',
    'BHOPAL': 'Madhya Pradesh', 'INDORE': 'Madhya Pradesh', 'REWA': 'Madhya Pradesh', 'SAGAR': 'Madhya Pradesh', 'GWALIOR': 'Madhya Pradesh', 'JABALPUR': 'Madhya Pradesh', 'UJJAIN': 'Madhya Pradesh',
    'PUNE': 'Maharashtra', 'NAGPUR': 'Maharashtra', 'MUMBAI': 'Maharashtra', 'AURANGABAD': 'Maharashtra', 'BARAMATI': 'Maharashtra', 'KALYAN': 'Maharashtra', 'NASHIK': 'Maharashtra',
    'IMPHAL': 'Manipur',
    'SHILLONG': 'Meghalaya',
    'AIZAWL': 'Mizoram',
    'KOHIMA': 'Nagaland',
    'BHUBANESWAR': 'Odisha', 'CUTTACK': 'Odisha',
    'LUDHIANA': 'Punjab', 'AMRITSAR': 'Punjab', 'PATIALA': 'Punjab', 'PATHANKOT': 'Punjab', 'BATHINDA': 'Punjab', 'JALANDHAR': 'Punjab', 'MOHALI': 'Punjab',
    'JODHPUR': 'Rajasthan', 'JAIPUR': 'Rajasthan', 'ALWAR': 'Rajasthan', 'KOTA': 'Rajasthan', 'BIKANER': 'Rajasthan', 'AJMER': 'Rajasthan', 'UDAIPUR': 'Rajasthan',
    'GANGTOK': 'Sikkim',
    'CHENNAI': 'Tamil Nadu', 'COIMBATORE': 'Tamil Nadu', 'MADURAI': 'Tamil Nadu', 'TIRUNELVELI': 'Tamil Nadu', 'SALEM': 'Tamil Nadu', 'CHENNAI NORTH': 'Tamil Nadu', 'CHENNAI SOUTH': 'Tamil Nadu', 'TRICHY': 'Tamil Nadu',
    'WARANGAL': 'Telangana', 'HYDERABAD': 'Telangana', 'HANUMAKONDA': 'Telangana', 'PEDDAPALLY': 'Telangana', 'KHAMMAM': 'Telangana', 'MAHABUBABAD': 'Telangana', 'NIRMAL': 'Telangana', 'NIZAMABAD': 'Telangana', 'MANCHERIAL': 'Telangana', 'KARIMNAGAR': 'Telangana', 'JANGAON': 'Telangana', 'KAMAREDDY': 'Telangana', 'JAGITYAL': 'Telangana', 'ADILABAD': 'Telangana', 'ASIFABAD': 'Telangana', 'BHADRADRI KOTHAGUDEM': 'Telangana', 'BHUPALAPALLY': 'Telangana',
    'AGARTALA': 'Tripura',
    'NOIDA': 'Uttar Pradesh', 'LUCKNOW': 'Uttar Pradesh', 'KANPUR': 'Uttar Pradesh', 'GHAZIABAD': 'Uttar Pradesh', 'AGRA': 'Uttar Pradesh', 'VARANASI': 'Uttar Pradesh', 'MEERUT': 'Uttar Pradesh',
    'DEHRADUN': 'Uttarakhand', 'HALDWANI': 'Uttarakhand',
    'KOLKATA': 'West Bengal', 'SILIGURI': 'West Bengal', 'ASANSOL': 'West Bengal', 'KOLKATA SOUTH': 'West Bengal', 'KOLKATA NORTH': 'West Bengal', 'HALDIA': 'West Bengal', 'HOWRAH': 'West Bengal', 'DURGAPUR': 'West Bengal',
    'CENTRAL DELHI': 'Delhi', 'SOUTH DELHI': 'Delhi',
    'SRINAGAR': 'Jammu & Kashmir', 'JAMMU': 'Jammu & Kashmir',
    'LEH': 'Ladakh', 'KARGIL': 'Ladakh',
    'CHANDIGARH': 'Chandigarh',
    'PUDUCHERRY': 'Puducherry',
    'PORT BLAIR': 'Andaman & Nicobar Islands',
    'SILVASSA': 'Dadra & Nagar Haveli',
    'DAMAN': 'Daman & Diu'
}
